version: '3.8'

services:
  backend:
    image: backend-image
    # Other configurations
    ports:
      - 8000:8000
    networks:
      - backend-network

  frontend:
    image: frontend-image
    ports:
      - 3000:3000
    networks:
      - frontend-network

networks:
  backend-network:
  frontend-network: